### ISSUE TITLE
Loading anyway malformed image when possible

### ISSUE THREAD

**Issue by Jehan** [pnggroup/libpng#200]
Hi!

We got a bug report in GIMP about PNGs which don't load well in GIMP: https://bugzilla.gnome.org/show_bug.cgi?id=776944
Loading the file available in the report outputs "IDAT: invalid distance too far back" and the image is only partially loaded.

If the image has some broken data, so it's ok to output warnings. But apparently there is still enough information to load fully the image and it has been reported that the images can even be fixed with command line tools such as optipng or pngcrush.

It would be much better than libpng allows to fully load the image while still outputting relevant warnings.

**Comment by brunvonlope** [comment]
Seems that this issue was solemnly ignored.

**Comment by ctruta** [comment]
Thanks @brunolopesdsilv for the poke.

Last time I hacked the tiniest piece of GIMP code was sometime in the year 2000. Understandably, my familiarity with it is virtually zero.

However, as the author of optipng, I can tell you that it used to use a modified and internally-vendored version of libpng, but that has no longer been the case in over a decade. I wish the libpng API made it more easy (it doesn't), but it's doable. Web browsers also load and display some of the image files that are partially broken.

If you'd like to contribute a suggestion for improved API that is sound and concrete, and preferably accompanied by a PR, I'll be super-interested.
