### ISSUE TITLE
Sourceforge release is lacking gpg signature

### ISSUE THREAD

**Issue by fenrus75** [pnggroup/libpng#244]
... previous releases had this

accident or hack?

**Comment by ctruta** [comment]
It's neither.
Glenn used to sign his releases using his GPG signature. For future releases I'll need to set up my own GPG key, but I haven't done that yet.

**Comment by eworm-de** [comment]
Recent releases are signed, but I can not find the key. Where to get it?

**Comment by ctruta** [comment]
> Recent releases are signed, but I can not find the key. Where to get it?

Whoops! I'll update the libpng website at SourceForge later today, and I'll ping the owner of libpng.org to update his website also. Ping you later.

**Comment by eworm-de** [comment]
Also please upload it to Github (and Gitlab). It will be available then: https://github.com/ctruta.gpg

**Comment by ctruta** [comment]
> Also please upload it to Github (and Gitlab). It will be available then: https://github.com/ctruta.gpg

Ha! I didn't know. Will do, thank you.

**Comment by ctruta** [comment]
Done, and thank you very much for asking.

**Comment by eworm-de** [comment]
Thanks a lot!
