### ISSUE TITLE
PNG and FLTK and WIN10

### ISSUE THREAD

**Issue by szukw000** [pnggroup/libpng#427]
I have an application that uses FLTK to show images. LINUX, MacOS and Pi4
did not fail with PNG images, although the libraries were patched with the
APNG-patch. The problem is with WIN10 using NMAKE.

Drawing PNG images I saw the application crashing under WIN10 only.

I sent a bug report to FLTK. They answered: not on our side.

I have now reduced the application to the PNG part, compiled the PNG library
without the APNG patch, and compiled the FLTK library with system libs, not
builtin libs. Finally I have found the following run log using WIN10:
```
//------------------------------------
 png_build_tree(..\adview.png) reader(000001AA41799990)
 version(1.6.38.git)
    png_ptr(000001AA417BC520) info_ptr(000001AA417C2E50)
 BEFORE png_read_info
//------------------------------------
```
There was no line 'AFTER png_read_info'.

'png_build_tree' uses a TREE widget of FLTK to show IHDR chunknames etc.

I do not know what is going on there. The least I expect is that png_read_info
returns with an error message. But nothing: it simply disappeares, and the
application crashes. The current PNG version for WIN10 is 1.6.38.git without
the APNG-patch.

winfried

**Comment by thealberto** [comment]
Hi @szukw000 ,
Do you have time to add additional `printf` inside `png_read_info` so you could identify where it fails?

Thanks

**Comment by szukw000** [comment]
@thealberto ,
here it is. The orignal line number is pngrio.c, 37.
winfried
[libpng-error.txt](https://github.com/glennrp/libpng/files/9419131/libpng-error.txt)

**Comment by thealberto** [comment]
Hi @szukw000 ,
Thanks a lot. Unfortunately atm I cannot work on it. Do you have any idea why it fails? It would be cool to recompile `libpng` with `asan` and `msan` and see what it says.

If you are interested to do it let us know. If not, no worries and I'll do it.

Thanks a lot for your help

**Comment by szukw000** [comment]
@thealberto ,

It is this line of code in pngrio.c, 60:
```
check = fread(data, 1, length, png_voidcast(png_FILE_p, png_ptr->io_ptr));
```
where the famous WIN10 fails.

winfried

**Comment by thealberto** [comment]
Hi @szukw000 ,
I haven't verified yet but I expect `length` to be too big for `data` so the program crashes... If you want you can investigate it further printing the length of `data` and the value of `length`. If you cannot, no worries and I'll do it in about 2 or 3 weeks.

Thanks

**Comment by jbowler** [comment]
@ctruta: Microsoft (FILE*) across runtimes bug again, I think (it's using default_read_data and only crashed on Windows).

**Comment by ctruta** [comment]
@jbowler I agree. I wonder if a (cheap and hacky) way to detect these kinds of crashes, ahead of time, exists. So if anything's suspicious, then print a warning.

Closing bug -- for now.

**Comment by jbowler** [comment]
There is a more extensive discussion elsewhere and that does have a suggested solution.  Basically change png_init_io into a macro which passes FILE*, &fread, &fwrite, &fflush to a png_init_io with a modified API and ABI to take the required parameters.  It needs implementing on the simplified API FILE* interface too but that's easy in 1.8.

I was thinking of something slightly broader which addressed the use of stderr in png_error too, so there would be a dependency on stdio in principle (pngstdio.c maybe) but it would be isolated, very isolated, and it would not actually end up calling any of the f functions in msvcrt[d].dll or glibc for that matter.

I just need 1.8 opened for activity :-)
