### ISSUE TITLE
libpng does not support PAC/BTI on aarch64 targets

### ISSUE THREAD

**Issue by rossburton** [pnggroup/libpng#505]
On aarch64/arm64, when we build with -mbranch-protection=standard to enable Pointer Authentication (PAC) and Branch Target Identification (BTI), the final link disables them because the assembler code doesn't support it.

This is mostly an exercise is annotating the branch and jump sites with `bti` instructions, and declaring that this has been done with a GNU segment note.

More information on :

PAC: https://developer.arm.com/documentation/102433/0100/Return-oriented-programming
BTI: https://developer.arm.com/documentation/102433/0100/Jump-oriented-programming

The problem can be replicated by adding `-mbranch-protection=standard` to `CFLAGS` (to enable the support in gcc) and `-z force-bti` to `LDFLAGS` (to make ld warn when it can't enable if asked).

**Comment by rossburton** [comment]
It appears that even when building for 64-bit targets `arm/filter_neon.S` is pulled into the build, so that will need a stub note or to be only pulled into 32-bit builds (as it doesn't support 64-bit arm anyway).

**Comment by jbowler** [comment]
Including arm/filter_neon.S is irrelevant; it contains no code unless PNG_ARM_NEON_IMPLEMENTATION has been set to 2 which, in the case of aarch64, should never be the case (see all the comments in pngpriv.h).

It's a bug in the compiler if a completely empty source file does this; it might be the ".section" directive I guess.

More analysis is required on your part; look at why the empty file is being included and why that causes problems.

**Comment by rossburton** [comment]
Right: the assembler creates a section, and that section has no PAC/BTI tags, so the compiler just respects that.

**Comment by rossburton** [comment]
Even a literally empty `.s` file is enough to generate an ELF without the required tags, so moving lines around won't help.

Removing `filter_neon.S` is probably the best solution, yes!

**Comment by jbowler** [comment]
@ctruta no feedback from the big guys in a month.  The change as constructed should cause build failures if anyone is using this stuff, but they will most likely fix it and not complain; I'm pretty sure the code is only applicable to builds (system+compiler) that are obsolete and the work-round is to not turn the code on by special (and obscure) build settings.

I recommend pulling this into the next libpng 1.6

**Comment by rossburton** [comment]
We may have found a problem in testing, I’ll double check and get back to you.

**Comment by jbowler** [comment]
Does this bug affect 32-bit ARM as well?

**Comment by billatarm** [comment]
> Does this bug affect 32-bit ARM as well?

No only aarch64 supports this feature. So it's as easy as at configure time detecting if we need the assembly file and adding it to the source list, this way we don't get an empty object file produced from the assembly file.

**Comment by jbowler** [comment]
> So it's as easy as at configure time

That's a better solution since the support is already there at line 424 of configure.ac (it just requires an extra AM_CONDITIONAL).  Likewise in CMakeLists.txt at line 138 - indeed cmake already does different things for <arm>64 vs just <arm>).

**Comment by billatarm** [comment]
I'll keep an eye out for the updated patch.

**Comment by ctruta** [comment]
Hello, I'm back, and my first item on the agenda was to apply your fix. (Thank you!)

Before we close this issue, I'd like to make sure I understand why not just remove `filter_neon.S` altogether. See my comment in PR #506.

**Comment by jbowler** [comment]
> Before we close this issue, I'd like to make sure I understand why not just remove `filter_neon.S` altogether.

That is the right approach in a major release but this is a bug-fix release.  In #506:

> Is anybody against the idea of removing filter_neon.S completely?

How do you hope to establish that no user of libpng 1.6 is against removing the file?  Bear in mind that there is no reason to remove the file other than tidiness, namely removal of (maybe) obsolete code.

There are no know bugs in **arm/filter_neon.S**; the bug is that it is hardware specific and it was being assembled for a different hardware.  The same bug exists for the code of other architectures; the code is compiled for AArch64 even though it is specific to a different architecture.  If anyone adds a ".S" file to one of those architectures this bug will reappear.

So the merged fix is a minimal fix (it doesn't fit all the other cases, which currently don't matter) and it doesn't presume that no one is using the ARM32 version.

The full fix is not to compile MIPS and PowerPC specific code for Intel, ARM32, AArch64 and Loongarch.  The latter might be difficult because Loongarch is just a fork of MIPS nevertheless since the merged fix demonstrates how the problem can be fixed for ARM32 and AArch64 (both Advanced Risc Machines products) MIPS should be able to achieve the same.

**Comment by ctruta** [comment]
Thank you, John, for summarizing. Now I understand. My answers are as follows:

 1. If it ain't broken, don't fix it.
 2. If it ain't tested, don't use it.

> How do you hope to establish that no user of libpng 1.6 is against removing the file?

So I reworked the contribution of @rossburton and @billatarm (in commit 9e538750d99c8f1accf7e93878e4fde47c069908), then I put back a stand-in (in commit e4a31f024b6158aaaf55a43502f574d5f5d1c894).

> Bear in mind that there is no reason to remove the file other than tidiness, namely removal of (maybe) obsolete code.

See the rule 2 above.

The old `filter_neon.S` was bit-rotten. Besides being left behind the alternative C implementation, the hand-made assembler was also breaking on the Android/ARMv7 build.

To be fair, I cannot know exactly what the users want. However, what I **do** know is what users **do not** want. Breakage in their workflow. (We're doing our best to avoid it.) The illusion that the ASM implementation is as good as the C implementation. (It wasn't.) The illusion that the ASM implementation is as well-tested as the C implementation. (It wasn't. Not formally tested by us inside, and not even battle-tested outside, apparently.) Not knowing exactly what to do when they discover any of the above. (We're telling them, in specifically-tailored `#error` messages.) Etc.

> So the merged fix is a minimal fix (it doesn't fit all the other cases, which currently don't matter) and it doesn't presume that no one is using the ARM32 version.

I have nothing against your fix, except for apologies, for obviating it afterwards... :-)
