### ISSUE TITLE
Need to restore STDERR in pngtest.c

### ISSUE THREAD

**Issue by bungeman** [pnggroup/libpng#560]
In [test: Add consistency checks for the PNG_LIBPNG_VER* number](https://github.com/pnggroup/libpng/commit/cc8006c48d90cca8bf380fa69469b08f4edb00c5) the `STDERR` macro was moved from outside an `#ifdef` to inside an `#ifdef`. This broke the code in the else of this `#ifdef` which also uses the `STDERR` macro. It appears the `#define STDERR` should be moved back to where it was to avoid compile errors in the `#else` case.

This can be reproduced by making a change similar to [what the oss-fuzz build currently does](https://github.com/pnggroup/libpng/blob/f1848a3b560ddcad065242268433af475948461e/contrib/oss-fuzz/build.sh#L29C11-L29C76) setting `option WRITE disabled` and then building.

**Comment by jbowler** [comment]
The modification in the second link in the original report is completely bogus; scripts/pnglibconf.dfa should never be modified!  It's part of the source code.  Attempting to claim a bug on the basis of a modification to the source code just doesn't work.

**Comment by jbowler** [comment]
@ctruta: here's the repro.  In the source tree:

```
mkdir test
cd test
../configure
DFA_XTRA=../contrib/conftest/simple.dfa make pnglibconf.h
make -j
make check
```

This fails with the reported error.   With cmake just copy simple.dfa on top of pngusr.dfa and do make -j

The bug exists in 1.6.43 which makes it a serious bug; it prevents running the check programs on a minconfig build.

**Comment by jbowler** [comment]
@ctruta: this is a major bug, the most significant bug, in 1.6.43
