### ISSUE TITLE
libpng-1.6.43.tar.gz is corrupt

### ISSUE THREAD

**Issue by Ron-eng90** [pnggroup/libpng#573]
I am loading gtkmm and it is downloading as a dependency, https://github.com/glennrp/libpng/v1.6.43.tar.gz and the resulting downloaded file, libpng-1.6.43.tar.gz is corrupt.   Is there a chance this will be fixed soon?  Thank you.

**Comment by jbowler** [comment]
No.  It's not corrupt, it is simply not there; click on the link you posted!  The tarballs are on sourceforge (in the libpng project) or you can simply **clone** the tag **v1.6.43** from here.  Note that the latter approach may not work in the future depending on Cosmin's decision about the checked in machine generated files.

**Comment by jbowler** [comment]
@Ron-eng90 please close this since it is resolved.
