### ISSUE TITLE
libpng-1.6.44 fails to compile with gcc 14 on armv7 target

### ISSUE THREAD

**Issue by xaviermiller** [pnggroup/libpng#598]
libpng-1.6.43 compiles fine, but I got this error with version 1.6.44, using Gentoo Linux on armv7 target:

libtool: compile:  armv7a-unknown-linux-gnueabihf-gcc -DHAVE_CONFIG_H -I. -I/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44 -O2 -pipe -mfloat-abi=hard -mfpu=vfpv3-d16 -mtls-dialect=gnu -mtune=cortex-a9 -marm -march=armv7-a+mp+sec+neon-fp16 -c /var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c  -fPIC -DPIC -o arm/.libs/filter_neon_intrinsics.o
In file included from /var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:24:
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h: In function 'paeth':
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:9245:1: error: inlining failed in call to 'always_inline' 'vbsl_u8': target specific option mismatch
 9245 | vbsl_u8 (uint8x8_t __a, uint8x8_t __b, uint8x8_t __c)
      | ^~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:282:8: note: called from here
  282 |    e = vbsl_u8(e, a, d);
      |        ^~~~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:9245:1: error: inlining failed in call to 'always_inline' 'vbsl_u8': target specific option mismatch
 9245 | vbsl_u8 (uint8x8_t __a, uint8x8_t __b, uint8x8_t __c)
      | ^~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:281:8: note: called from here
  281 |    d = vbsl_u8(d, b, c);
      |        ^~~~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:7612:1: error: inlining failed in call to 'always_inline' 'vmovn_u16': target specific option mismatch
 7612 | vmovn_u16 (uint16x8_t __a)
      | ^~~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:279:8: note: called from here
  279 |    e = vmovn_u16(p1);
      |        ^~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:7612:1: error: inlining failed in call to 'always_inline' 'vmovn_u16': target specific option mismatch
 7612 | vmovn_u16 (uint16x8_t __a)
      | ^~~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:278:8: note: called from here
  278 |    d = vmovn_u16(pb);
      |        ^~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:15231:1: error: inlining failed in call to 'always_inline' 'vandq_u16': target specific option mismatch
15231 | vandq_u16 (uint16x8_t __a, uint16x8_t __b)
      | ^~~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:276:9: note: called from here
  276 |    p1 = vandq_u16(p1, pa); /* pa <= pb && pa <= pc */
      |         ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:2662:1: error: inlining failed in call to 'always_inline' 'vcleq_u16': target specific option mismatch
 2662 | vcleq_u16 (uint16x8_t __a, uint16x8_t __b)
      | ^~~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:274:9: note: called from here
  274 |    pb = vcleq_u16(pb, pc); /* pb <= pc */
      |         ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:2662:1: error: inlining failed in call to 'always_inline' 'vcleq_u16': target specific option mismatch
 2662 | vcleq_u16 (uint16x8_t __a, uint16x8_t __b)
      | ^~~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:273:9: note: called from here
  273 |    pa = vcleq_u16(pa, pc); /* pa <= pc */
      |         ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:2662:1: error: inlining failed in call to 'always_inline' 'vcleq_u16': target specific option mismatch
 2662 | vcleq_u16 (uint16x8_t __a, uint16x8_t __b)
      | ^~~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:272:9: note: called from here
  272 |    p1 = vcleq_u16(pa, pb); /* pa <= pb */
      |         ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:3253:1: error: inlining failed in call to 'always_inline' 'vabdq_u16': target specific option mismatch
 3253 | vabdq_u16 (uint16x8_t __a, uint16x8_t __b)
      | ^~~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:270:9: note: called from here
  270 |    pc = vabdq_u16(p1, pc); /* pc */
      |         ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:3288:1: error: inlining failed in call to 'always_inline' 'vabdl_u8': target specific option mismatch
 3288 | vabdl_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:269:9: note: called from here
  269 |    pb = vabdl_u8(a, c); /* pb */
      |         ^~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:3288:1: error: inlining failed in call to 'always_inline' 'vabdl_u8': target specific option mismatch
 3288 | vabdl_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:268:9: note: called from here
  268 |    pa = vabdl_u8(b, c); /* pa */
      |         ^~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:686:1: error: inlining failed in call to 'always_inline' 'vaddl_u8': target specific option mismatch
  686 | vaddl_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:267:9: note: called from here
  267 |    pc = vaddl_u8(c, c); /* c * 2 */
      |         ^~~~~~~~~~~~~~
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/14/include/arm_neon.h:686:1: error: inlining failed in call to 'always_inline' 'vaddl_u8': target specific option mismatch
  686 | vaddl_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44/arm/filter_neon_intrinsics.c:266:9: note: called from here
  266 |    p1 = vaddl_u8(a, b); /* a + b */
      |         ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1274: arm/filter_neon_intrinsics.lo] Error 1
make[1]: Leaving directory '/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44-.arm'
make: *** [Makefile:886: all] Error 2
 * ERROR: media-libs/libpng-1.6.44::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=media-libs/libpng-1.6.44::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=media-libs/libpng-1.6.44::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/media-libs/libpng-1.6.44/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-libs/libpng-1.6.44/temp/environment'.
 * Working directory: '/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44-.arm'
 * S: '/var/tmp/portage/media-libs/libpng-1.6.44/work/libpng-1.6.44'

>>> Failed to emerge media-libs/libpng-1.6.44, Log file:

**Comment by xaviermiller** [comment]
[build.log](https://github.com/user-attachments/files/17047585/build.log)

**Comment by jbowler** [comment]
You need to report this to Gentoo, not here.  For one thing they will insist you do what it says in the last few lines of this issue (like include all the build configuration information!)

At present the gentoo status is here:

https://packages.gentoo.org/packages/media-libs/libpng

ARM (i.e. ARM32) is only "green" with 1.6.43.  Indeed on Intel my portage tree only shows 1.6.43, so I assume "yellow" means not yet available even to those of use who use the development releases (i.e. ~arm in this case.)

@ctruta: please close this, it needs to go to gentoo along with all the information that is required to repro a bug on gentoo.

**Comment by jbowler** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=939819

I added a brief explanation there (well, I suggested removing --enable-arm-neon :-)  It's a side effect of the security issue #505, the fix #506 and the first of the two commits, https://github.com/pnggroup/libpng/commit/9e538750d99c8f1accf7e93878e4fde47c069908
