### ISSUE TITLE
aarch64-linux-gnu-gcc Cross-compile won't work

### ISSUE THREAD

**Issue by famoustang** [pnggroup/libpng#599]
When cross-compiling with aarch64-Linux-gnu-gcc on ubuntu, the syntax of CMakeLists.txt causes the host CPU type to be used against the cross-compiled target type, resulting in parts of arm-neon code not being compiled 。

The target type support is passed in by modifying the configuration of CMakeLists.txt to handle the misjudgment and be compatible with the current code state 

\# in a single CMake invocation.
if (APPLE AND CMAKE_OSX_ARCHITECTURES)
&emsp;string(TOLOWER "${CMAKE_OSX_ARCHITECTURES}" PNG_TARGET_ARCHITECTURE)
else()
&emsp;#There is an issue here, if you use the x86_64 platform for cross-compilation, the arm version of the function will not be compiled, resulting in compilation failure 
&emsp;if(NOT DEFINED PNG_TARGET_ARCHITECTURE)
&emsp;&emsp;string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" PNG_TARGET_ARCHITECTURE)
&emsp;endif()
endif()
message(STATUS "Building for target architecture: ${PNG_TARGET_ARCHITECTURE}")

**Comment by jbowler** [comment]
@ctruta: **duplicate** of #372, fixed by #575, please close as **duplicate** [i.e. "will not be fixed", or "fixed if you define PNG_TARGET_ARCHITECTURE" or "fixed in libpng 1.8"]

**Comment by famoustang** [comment]
fixed if you define PNG_TARGET_ARCHITECTURE
